- src: https://github.com/traveloka/ansible-mongod-3.6
  name: mongod-3.6
- src: https://github.com/traveloka/ansible-xfsvolume
  name: xfsvolume
- src: https://github.com/traveloka/ansible-awslogs-config
  name: awslogs-config
- src: https://github.com/traveloka/ansible-mongodb-root-user
  name: mongo-root-user
- src: https://github.com/traveloka/ansible-datadog-agent
  name: datadog
- src: https://github.com/traveloka/ansible-datadog-configure-mongo-custom
  name: datadog-mongo-checks
